services:
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        networks:
            - node-red-net
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
    node-red:
        image: nodered/node-red:latest
        environment:
            - TZ=Europe/Warsaw
        networks:
            - node-red-net
        ports:
            - "1880:1880"
        volumes:
            - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net: