services:
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        networks:
            - iot-plant-net
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
    node-red:
        build: .
        networks:
            - iot-plant-net
        ports:
            - "1880:1880"
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

networks:
  iot-plant-net: